#ifndef RAW_INPUT_CONSTANTS_H
#define RAW_INPUT_CONSTANTS_H

#include "Fizzle\DataTypes\FizzleDataTypes.h"
#include <map>
#include <string>

namespace InputMapping
{

	enum RawInputAxis
	{
		RAW_INPUT_AXIS_MOUSE_X,
		RAW_INPUT_AXIS_MOUSE_Y,
	};

	const std::map<std::string, RawInputAxis> RawInputAxisMap
	{
		{"RAW_INPUT_AXIS_MOUSE_X", RAW_INPUT_AXIS_MOUSE_X},
		{"RAW_INPUT_AXIS_MOUSE_Y", RAW_INPUT_AXIS_MOUSE_Y},
	};

	const std::map<std::string, FzlKey>FzlMap
	{
		{ "FzlKeySpace", FzlKeySpace },
		{ "FzlKeyApostrophe", FzlKeyApostrophe },
		{ "FzlKeyComma", FzlKeyComma },
		{ "FzlKeyMinus", FzlKeyMinus },
		{ "FzlKeyPeriod", FzlKeyPeriod },
		{ "FzlKeySlash", FzlKeySlash },
		{ "FzlKeyNumRow0", FzlKeyNumRow0 },
		{ "FzlKeyNumRow1", FzlKeyNumRow1 },
		{ "FzlKeyNumRow2", FzlKeyNumRow2 },
		{ "FzlKeyNumRow3", FzlKeyNumRow3 },
		{ "FzlKeyNumRow4", FzlKeyNumRow4 },
		{ "FzlKeyNumRow5", FzlKeyNumRow5 },
		{ "FzlKeyNumRow6", FzlKeyNumRow6 },
		{ "FzlKeyNumRow7", FzlKeyNumRow7 },
		{ "FzlKeyNumRow8", FzlKeyNumRow8 },
		{ "FzlKeyNumRow9", FzlKeyNumRow9 },
		{ "FzlKeySemicolon", FzlKeySemicolon },
		{ "FzlKeyEquals", FzlKeyEquals },
		{ "FzlKeyA", FzlKeyA },
		{ "FzlKeyB", FzlKeyB },
		{ "FzlKeyC", FzlKeyC },
		{ "FzlKeyD", FzlKeyD },
		{ "FzlKeyE", FzlKeyE },
		{ "FzlKeyF", FzlKeyF },
		{ "FzlKeyG", FzlKeyG },
		{ "FzlKeyH", FzlKeyH },
		{ "FzlKeyI", FzlKeyI },
		{ "FzlKeyJ", FzlKeyJ },
		{ "FzlKeyK", FzlKeyK },
		{ "FzlKeyL", FzlKeyL },
		{ "FzlKeyM", FzlKeyM },
		{ "FzlKeyN", FzlKeyN },
		{ "FzlKeyO", FzlKeyO },
		{ "FzlKeyP", FzlKeyP },
		{ "FzlKeyQ", FzlKeyQ },
		{ "FzlKeyR", FzlKeyR },
		{ "FzlKeyS", FzlKeyS },
		{ "FzlKeyT", FzlKeyT },
		{ "FzlKeyU", FzlKeyU },
		{ "FzlKeyV", FzlKeyV },
		{ "FzlKeyW", FzlKeyW },
		{ "FzlKeyX", FzlKeyX },
		{ "FzlKeyY", FzlKeyY },
		{ "FzlKeyZ", FzlKeyZ },
		{ "FzlKeyLeftBracket", FzlKeyLeftBracket },
		{ "FzlKeyBackslash", FzlKeyBackslash },
		{ "FzlKeyRightBracket", FzlKeyRightBracket },
		{ "FzlKeyGraveAccent", FzlKeyGraveAccent },
		{ "FzlKeyEscape", FzlKeyEscape },
		{ "FzlKeyEnter", FzlKeyEnter },
		{ "FzlKeyTab", FzlKeyTab },
		{ "FzlKeyBackspace", FzlKeyBackspace },
		{ "FzlKeyInsert", FzlKeyInsert },
		{ "FzlKeyDelete", FzlKeyDelete },
		{ "FzlKeyRightArrow", FzlKeyRightArrow },
		{ "FzlKeyLeftArrow", FzlKeyLeftArrow },
		{ "FzlKeyDownArrow", FzlKeyDownArrow },
		{ "FzlKeyUpArrow", FzlKeyUpArrow },
		{ "FzlKeyPageUp", FzlKeyPageUp },
		{ "FzlKeyPageDown", FzlKeyPageDown },
		{ "FzlKeyHome", FzlKeyHome },
		{ "FzlKeyEnd", FzlKeyEnd },
		{ "FzlKeyCapsLock", FzlKeyCapsLock },
		{ "FzlKeyScrollLock", FzlKeyScrollLock },
		{ "FzlKeyNumLock", FzlKeyNumLock },
		{ "FzlKeyPrintScreen", FzlKeyPrintScreen },
		{ "FzlKeyPause", FzlKeyPause },
		{ "FzlKeyF1", FzlKeyF1 },
		{ "FzlKeyF2", FzlKeyF2 },
		{ "FzlKeyF3", FzlKeyF3 },
		{ "FzlKeyF4", FzlKeyF4 },
		{ "FzlKeyF5", FzlKeyF5 },
		{ "FzlKeyF6", FzlKeyF6 },
		{ "FzlKeyF7", FzlKeyF7 },
		{ "FzlKeyF8", FzlKeyF8 },
		{ "FzlKeyF9", FzlKeyF9 },
		{ "FzlKeyF10", FzlKeyF10 },
		{ "FzlKeyF11", FzlKeyF11 },
		{ "FzlKeyF12", FzlKeyF12 },
		{ "FzlKeyNumPad0", FzlKeyNumPad0 },
		{ "FzlKeyNumPad1", FzlKeyNumPad1 },
		{ "FzlKeyNumPad2", FzlKeyNumPad2 },
		{ "FzlKeyNumPad3", FzlKeyNumPad3 },
		{ "FzlKeyNumPad4", FzlKeyNumPad4 },
		{ "FzlKeyNumPad5", FzlKeyNumPad5 },
		{ "FzlKeyNumPad6", FzlKeyNumPad6 },
		{ "FzlKeyNumPad7", FzlKeyNumPad7 },
		{ "FzlKeyNumPad8", FzlKeyNumPad8 },
		{ "FzlKeyNumPad9", FzlKeyNumPad9 },
		{ "FzlKeyNumPadDecimal", FzlKeyNumPadDecimal },
		{ "FzlKeyNumPadDivide", FzlKeyNumPadDivide },
		{ "FzlKeyNumPadMultiply", FzlKeyNumPadMultiply },
		{ "FzlKeyNumPadSubtract", FzlKeyNumPadSubtract },
		{ "FzlKeyNumPadAdd", FzlKeyNumPadAdd },
		{ "FzlKeyNumPadEnter", FzlKeyNumPadEnter },
		{ "FzlKeyNumPadEquals", FzlKeyNumPadEquals },
		{ "FzlKeyLeftShift", FzlKeyLeftShift },
		{ "FzlKeyLeftCtrl", FzlKeyLeftCtrl },
		{ "FzlKeyLeftAlt", FzlKeyLeftAlt },
		{ "FzlKeyRightShift", FzlKeyRightShift },
		{ "FzlKeyRightCtrl", FzlKeyRightCtrl },
		{ "FzlKeyRightAlt", FzlKeyRightAlt },
	};

}

#endif